### PR TITLE
Fixed #152. 

### LINKED ISSUE #152: Yum cache should be purged before repository config file is deleted
The `yum clean` command only operates against repositories that are currently defined and enabled.
From the yum man page:
>CLEAN OPTIONS
>       The following are the ways which you can invoke yum in clean mode. Note
>       that  "all  files"  in the commands below means "all files in currently
>       enabled repositories".  If you want to  also  clean  any  (temporarily)
>       disabled repositories you need to use --enablerepo=’*’ option.

In the provider, the repository config file is deleted and then the cache is cleaned; however, this means that the cache is left intact for the cache that you just removed.
It looks like the provider is trying to explicitly enable the deleted repo, but if you try this on a box with a repo that's undefined, you get an error:

```
[root@server01 yum]# yum clean all --disablerepo=* --enablerepo=chef_stable
Loaded plugins: security


Error getting repository data for chef_stable, repository not found
```

The provider should try to flush the cache first, delete the repository file, and then reload the cache.

A `:before` timer could be used instead of `:immediately`, but that is only supported in Chef 12+ somewhere. Alternatively, an `only_if` block could be used to test for the file's existence, which would preserve chef 11 support.

### PR DESCRIPTION
**Pull request by iancward**
### Description

Flush the yum cache _before _ deleting the repository

### Issues Resolved

#152 

### Check List
- [X] All tests pass. See https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD
- [X] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [X] The Commit(s) have been signed off per the DCO. See https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD

Flush the yum cache before deleting the repo config file

### CODE REVIEW

**Comment by iancward** [comment]
It looks like some of the failures are related to the rpmfusion repo not having a baseurl; I'm not sure why this failed, as a mirrorlist is provided.

When I tested this back in March, Chefspec executed cleanly. Have the recent changes to this cookbook broken them?

**Comment by haidangwa** [comment]
Before this is accepted, it needs to address the cache directories that are created by yum when those repos were active. `yum clean all` merely deletes the files, not the directories. This would create an eventual clutter of empty cache directories over a period of time. See my comment in the bug report with sample code: https://github.com/chef-cookbooks/yum/issues/152#issuecomment-248402068

**Comment by iancward** [comment]
I'd rather let the tool handle this than try to forcibly delete stuff that may actually be useful or what should be left there. From looking at this, it appears that the only thing that `yum clean all` doesn't remove is the directory that the cache lived in.

**Comment by haidangwa** [comment]
that's the point I'm making is that "the tool" (i.e., yum), does not deal with the empty cache directories. The repo's cache directory is left behind after this is "cleaned". This would fall under a complete solution. There would be no reason to leave those empty directories behind; especially, as the next steps are to remove the repo's yum config file, as well.  The proposed procedure, in all intents and purposes, leaves no trace of the repo, except for these empty cache directories.

**Comment by iancward** [comment]
The yum cache dir isn't known to the yum_repository provider, so we'd have to dig it out of the yum config. That just seems like a lot of work to remove an empty directory.

**Comment by tas50** [comment]
I'm fine with performing the level of cleanup that yum itself handles. Cleaning up the directories is really beyond this and has pretty limited value since they take up no disk space.

**Comment by tas50** [comment]
@iancward Any chance you can make this same change to https://github.com/chef/chef as well? The yum_repository provider is built into chef now so the change in this cookbook will only apply to pre Chef 12.14 clients now.

**Comment by iancward** [comment]
@tas50 I opened https://github.com/chef/chef/issues/5459 and I have some code ready and going through my company's internal process to get approval to submit it.

**Comment by iancward** [comment]
@tas50 sorry for the delay on this. I just got approval last night so I opened https://github.com/chef/chef/pull/5509.

**Pull request merged**
